version: '3.8'

services:
  gate:
    build: .
    container_name: gatea
    image: gate
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
